services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppassword
      MARIADB_DATABASE: supportjoin
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d   # SQL scripts
      - mariadb_data:/var/lib/mysql           # Persistent database storage
    command: ["--transaction-isolation=READ-COMMITTED", "--log-bin=binlog"] # optional tuning

  springboot-app:
    build: .
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/supportjoin
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppassword
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    volumes:
      - ./entrypoint.sh:/tmp/entrypoint.sh
    command: ["sh", "/tmp/entrypoint.sh"]
    restart: on-failure

volumes:
  mariadb_data: